ports:
  - port: 7900
tasks:
  - before: |
      # install poetry
      curl -sSL https://install.python-poetry.org | python3 -
    
      # add command line completions
      echo ". <(poetry completions bash)" >> /home/gitpod/.bashrc
      poetry self update
      poetry install
  - init: |
      docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:4.1.4-20220427
  - command: |
      poetry run python3 init.py