ports:
  - port: 7900
  - port: 4444
    visibility: public
tasks:
  - before: |
      # install poetry
      curl -sSL https://install.python-poetry.org | python3 -
    
      # add command line completions
      echo ". <(poetry completions bash)" >> /home/gitpod/.bashrc
      poetry self update
      poetry install
  - init: |
      docker run --rm -d --name selenium-docker -p 4444:4444 --shm-size="2g" \
      -v ${PWD}/selenium/config.toml:/opt/bin/config.toml \
      -v ${PWD}/selenium/assets:/opt/selenium/assets \
      -v /var/run/docker.sock:/var/run/docker.sock \
      selenium/standalone-docker:4.1.4-20220427
  - command: |
      poetry run python3 init.py